apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: draft-app

configMapGenerator:
  - name: app-configmap
    envs:
      - config.env

generatorOptions:
    disableNameSuffixHash: true